### PR TITLE
recipes: update gazeta prawna recipe

### PR DESCRIPTION
**Pull request by tjozwiak**
This patch removes obsolete 'gazeta-prawna-calibre-v1.recipe'
and adds new one gazeta-prawna-calibre-new.recipe instead

Signed-off-by: Tomasz Jozwiak <tjozwiakgm@gmail.com>

### CODE REVIEW

**Comment by kovidgoyal** [comment]
You should not rename the recipe file, just replace its contents.

**Comment by tjozwiak** [comment]
Hi, Thx for your comment. I've changed the file name cause this file was absolutely obsolete and suggests first version of something. Also the author of this file is uknow now. To keep this file we also should keep the author. So may be better is create new name. What do you think?

**Comment by tjozwiak** [comment]
BTW I've changed probably everything in this file :)

**Comment by kovidgoyal** [comment]
Creating a new name means that any user that has scheduled the recipe
for download will no longer be able to schedule it and will have to redo
the schedule. Feel free to change the author in the existing recipe
file, if you have completely re-written it.

**Comment by tjozwiak** [comment]
ok

**Pull request merged**
