### PR TITLE
amazon parser: store all product details

### PR DESCRIPTION
**Pull request by milahu**
i needed a generic amazon parser to get all product details
so these are now stored in `mi._details`

also fixed some other stuff, probably not all will be merged

<details>
<summary>
example use
</summary>

```py
#!/usr/bin/env python3

# based on /nix/store/q220vq57bgpijr7qbymhcv8b26jb861n-calibre-7.10.0/bin/.calibre-wrapped

import sys, os



# set calibre paths

calibre_source = os.path.dirname(__file__) + "/calibre"
calibre_prefix = "/nix/store/q220vq57bgpijr7qbymhcv8b26jb861n-calibre-7.10.0"

#path = os.environ.get('CALIBRE_PYTHON_PATH', calibre_prefix + '/lib/calibre')
path = os.environ.get('CALIBRE_PYTHON_PATH', calibre_source + "/src")
if path not in sys.path:
    sys.path.insert(0, path)

#sys.resources_location = os.environ.get('CALIBRE_RESOURCES_PATH', calibre_prefix + "/share/calibre")
sys.resources_location = os.environ.get('CALIBRE_RESOURCES_PATH', calibre_source + "/resources")

sys.extensions_location = os.environ.get('CALIBRE_EXTENSIONS_PATH', calibre_prefix + '/lib/calibre/calibre/plugins')

sys.executables_location = os.environ.get('CALIBRE_EXECUTABLES_PATH', calibre_prefix + '/bin')

sys.system_plugins_location = None



#from calibre.gui_launch import calibre
#sys.exit(calibre())

url = sys.argv[1]
cache_path = sys.argv[2]

import calibre.ebooks.metadata.sources.amazon

import calibre.utils.browser

import calibre.utils.logging

log = calibre.utils.logging.Log()

#import traceback

def log_exception(self, *args, **kwargs):
    limit = kwargs.pop('limit', None)
    print(*args, **kwargs)
    #print(traceback.format_exc(limit))
    raise

log.exception = log_exception

import queue
result_queue = queue.Queue()

# Get book details from amazons book page
worker = calibre.ebooks.metadata.sources.amazon.Worker(
    url,
    result_queue,
    browser=calibre.utils.browser.Browser(),
    log=log,
    relevance=None,
    domain=None,
    plugin=None,
    #timeout=20,
    #testing=False,
    #preparsed_root=None,
    #cover_url_processor=None,
    #filter_result=None
    cache_path=cache_path,
)

worker.run()
print("result_queue", result_queue)

mi = result_queue.get()
print("mi")
print(mi)
print("details")
for key, val in mi._details.items():
    print(f"{key}: {val}")
```

</details>

### CODE REVIEW

**Comment by kovidgoyal** [comment]
I am not going to commit to maintaining parsing of metadata from amazon that calibre doesnt use. As for the rest of your fixes, I cant see how any of them are relevant, or even correct. For example, the ISO 639-2 standard code for german is both deu and ger. So why prefer ger? Why special case formatting of zero times in isoformat? And doing so means yur datetime becomes naive losing timezone information. Why change Authors(s) to Authors?

**Comment by milahu** [comment]
these may be useful

https://github.com/kovidgoyal/calibre/pull/2316/commits/518b92131ccafae43cd0fdcc21d5674861f21d72
https://github.com/kovidgoyal/calibre/commit/73a9485544cfd2979f393ae6162d9475a2bba826

**Comment by kovidgoyal** [comment]
The rating is correct already.  Source plugins are supposed to return values on a scale of 10, they get normalized by other code in the pipeline.  I have merged the audiobooks one, thanks.

**Comment by milahu** [comment]
> The rating is correct already.

fails in at least 2 cases
https://www.amazon.de/-/en/dp/B086GX5SNN
https://www.amazon.de/-/en/dp/3954714493

also https://github.com/kovidgoyal/calibre/commit/35b409a880e19837ccea95011f529e14def91464 to avoid exceptions

**Comment by kovidgoyal** [comment]
On Sun, Jun 23, 2024 at 06:10:13AM -0700, milahu wrote:
> > The rating is correct already.
>
> fails in at least 2 cases
> https://www.amazon.de/-/en/dp/B086GX5SNN

Gives me a rating of 4.5 as expected, running via command line.

> https://www.amazon.de/-/en/dp/3954714493
>
> also https://github.com/kovidgoyal/calibre/commit/35b409a880e19837ccea95011f529e14def91464 to avoid exceptions

What exception does that avoid?

**Comment by milahu** [comment]
> Gives me a rating of 4.5 as expected

no, rating should be 4.7 * 2 = 9.4 of 10

https://www.amazon.de/-/en/dp/B086GX5SNN

> 4.7 out of 5 stars

with calibre master
`mi.rating` is 4.7 of 5
also `print(mi)` says `Rating              : 4.7`

with https://github.com/kovidgoyal/calibre/commit/518b92131ccafae43cd0fdcc21d5674861f21d72 and https://github.com/kovidgoyal/calibre/commit/a5fdcb35b3defef4dec491a434d9a7cb62dd71dd
`mi.rating` is 9.4 of 10
but `print(mi)` still says `Rating              : 9.4`

> running via command line

im calling `calibre.ebooks.metadata.sources.amazon.Worker` directly
see my first comment

> What exception does that avoid?

`dateutil.parser._parser.ParserError: Unknown string format: Some Publisher`
via `self.log.exception('Failed to parse pubdate: %s' % val)`

**Comment by milahu** [comment]
also a2bbd5582f2b0dd05a1f116d43c241ac02e69667

**Comment by kovidgoyal** [comment]
On Sun, Jun 23, 2024 at 06:50:33AM -0700, milahu wrote:
>
> > Gives me a rating of 4.5 as expected
>
> no, rating should be 4.7 * 2 = 9.4 of 10

No its an *integer* between 0 and 10. Which in this case is 9 int(9.4).
And 9 becomes an effective rating of 4.5

**Comment by milahu** [comment]
> effective rating of 4.5

its confusing when "rating" can be 5-based or 10-based

> ... or rating should be renamed to stars
> to separate 10-based from 5-based values
>
> ... or all ratings should be 5-based to make it consistent

**Pull request closed without merging**
