### PR TITLE
As I discussed in the previous PR, this commit makes the cover adapt …

### PR DESCRIPTION
**Pull request by cbhaley**
…to the new area when the book details pane changes size. I used the same technique you used in .widgets.

### CODE REVIEW

**Comment by cbhaley** [comment]
Your change to use a style doesn't work on Windows 10. Do I need a new binary?

**Comment by kovidgoyal** [comment]
yes, this needs a new binary as the custom drawing now happens in C++ code.

**Comment by cbhaley** [comment]
OK, I will wait for a new beta or the next release, whichever comes first.

**Comment by kovidgoyal** [comment]
Yes, one can theoretically set a proxystyle via Python, but performance
is really bad and you dont get access to various low level Qt things
that are needed sometimes for custom rendering of components. So it's
implemented in C++ in calibre.

**Comment by kovidgoyal** [comment]
On Wed, Oct 26, 2022 at 08:50:46AM -0700, Charles Haley wrote:
> Your change to use a style doesn't work on Windows 10. Do I need a new binary?

I uploaded a new beta build, so you can try it out if you like.

**Comment by kovidgoyal** [comment]
Actually, no the build process failed, so I will update the builds later today.

**Comment by kovidgoyal** [comment]
Finally got the build working again so new beta is uploaded. Incidentally do you have a way to test the smart_device driver still? There was a report that the beta is crashing with it on MR

**Pull request merged**
