### PR TITLE
Ensure that the correct keyboard shortcut is shown in the layout buttons

### PR DESCRIPTION
**Pull request by cbhaley**

### CODE REVIEW

**Comment by cbhaley** [comment]
Pushed a small change to fix a potential problem with subclasses of LayoutButton

**Comment by kovidgoyal** [comment]
Wouldn't it be easier to just connect to the changed() signal of the QAction and update the tooltip?

**Comment by cbhaley** [comment]
Very possibly. I didn't know that the action changed signal was emitted when shortcuts changed. I will investigate.

**Comment by kovidgoyal** [comment]
I pushed a patch using the changed signal, I haven't actually tested it though

**Pull request closed without merging**
