### PR TITLE
Updating for reduced image sizes

### PR DESCRIPTION
**Pull request by bobbysteel**
Changes to the website have greatly increased image sizes, so implementing in-built filesize reduction through image compression.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
I dont like the idea of compressing news images unconditionally in recipes. As time passes, screens become higher resolution. So having higher resolution images in the source is a good thing. About the only legitimate use for post-download image compression I can think of, is amazon's arbitrary file size limits for emailing books. Given that emailing news files also destroys periodical formatting, I am not particularly sympathetic to this use case.

**Comment by bobbysteel** [comment]
Well right now the current recipe delivers a 60MB file which is too big for
sending to Kindle in any circumstance.

**Comment by bobbysteel** [comment]
And the new file w/ these flags looks entirely the same as before. No
changes in result.

**Comment by kovidgoyal** [comment]
What nonsense, the Kindle can handle 60MB files perfectly well. Just send it using a USB connection.

**Comment by bobbysteel** [comment]
Yes it can handle but who uses a wired cable to load files? Their wireless
sending is the key feature.

**Comment by kovidgoyal** [comment]
Who uses email delivery -- its a horrible feature that is limited in size, accepts only old style mobi files, causes periodical formatting to be destroyed and fails randomly because of amazons spam controls. 

You want wireless delivery use the content server the kindle browser can download mobi files from it just fine.

**Comment by bobbysteel** [comment]
Haha, tell that to Amazon. They accept via email or their SendToKindle
uploader which caps at 50MB. It works flawlessly and has for me and many
friends for many years. I suspect many of your users for news would use the
email-to-kindle versus setting up their own content server. A content
server is needless for almost any Kindle user.

You seem to be taking this very personally. It's an Amazon construct, not
dumb users.

**Comment by kovidgoyal** [comment]
You seem to be confused. I have told you why I dont like the idea of forcing everyone to use lower quality images to accomodate amazon's brokenness, in the very first post. You are responding with telling me that it's amazon's fault. I know that already. Once again,

I dont want to make all calibre users suffer for something that is amazon's fault. 

And there is no "setup" for a content server. It's a single button to click in calibre.

**Comment by kovidgoyal** [comment]
What I am willing to do is turn on the compression conditionally if the output profile is set to a kindle profile.

**Comment by bobbysteel** [comment]
i take your point but a content server requires at a minimum a PC on 24/7
and a firewall configuration.

shrug. doesn't really matter as i have my own custom recipe, but i expected
this would help many more of your users that are on Kindle. i'll just go
away now.

**Comment by bobbysteel** [comment]
that's very sensible.

**Comment by bobbysteel** [comment]
i'm happy to code and submit a PR for that if you can point me to where the
conditional logic for this is similarly used. :)

**Comment by kovidgoyal** [comment]
Dont worry, I'll take care of it :)

**Comment by bobbysteel** [comment]
Thanks Kovid. As always I (and many others) highly appreciate all your work!

**Pull request closed without merging**
