### PR TITLE
Update Science Journals

### PR DESCRIPTION
**Pull request by unkn0w7n**
reduced image size, option to change img-res

also added economist search recipe.

### CODE REVIEW

**Comment by unkn0w7n** [comment]
does `br.addheaders` in `def get_browser` work for `browser_type = 'webengine'`?
I feel like its not working.

**Comment by kovidgoyal** [comment]
It should as far as I know. You can add a test for it in
test_fetch_backend.py if you like to verify.

**Comment by kovidgoyal** [comment]
In fact ther eis already a test for it. addheaders is set by the headers
paramater passed to __init__ which sets the th: 1 header which is sent
by both qt and webengine backends.

**Comment by unkn0w7n** [comment]
hmm.. I'll check again.. maybe the issue is something else.

**Pull request merged**
