### PR TITLE
python3: misc polyglot fixes

### PR DESCRIPTION
**Pull request by eli-schwartz**
Add more wrappers for urllib, queue.
Remove dead code.

In #941 I overlooked two files that are in metadata/sources/ but they aren't actually metadata plugins and aren't dynamically updated, so it should be safe to use polyglot there.

Question: html2text is currently under active development after it found a new maintainer, is it suitable in its current state to be used directly?

### CODE REVIEW

**Comment by kovidgoyal** [comment]
there is a typo in feeds.news (urlplit)

**Comment by eli-schwartz** [comment]
Indeed there is, fixed.

Also turns out src/calibre/devices/manager.py has code that does not seem to be used anywhere? But was trying to `import Queue; Queue(0)`.

**Comment by kovidgoyal** [comment]
I have removed devices/manager.py as it is indeed, unused.

**Comment by kovidgoyal** [comment]
I have also de-vendored html2text.

**Comment by kovidgoyal** [comment]
rebase on master and I will merge.

**Comment by eli-schwartz** [comment]
Done, and thanks.

**Pull request merged**
