### PR TITLE
URL has changed for current online issue

### PR DESCRIPTION
**Pull request by Sophist-UK**
Not able to test as have not setup a dev env on my PC - but old URL is causing 404 errors.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
You dont need a dev env to test recipes, see https://manual.calibre-ebook.com/news.html

**Comment by kovidgoyal** [comment]
Sorry make that https://manual.calibre-ebook.com/news.html#tips-for-developing-new-recipes

**Comment by Sophist-UK** [comment]
Ok - have tested it and it doesn't work. the URL change was wrong - underscore has changed to hyphen, but even with that changed it still doesn't work.

Please revert and I will try to get it working and submit a new PR.

**Comment by kovidgoyal** [comment]
No need to revert since it wasn't working in the first place, no great loss. Just submit a new PR whenever you are ready.

**Pull request merged**
