### PR TITLE
[add][recipe] Adding RSS source for reflex.cz

### PR DESCRIPTION
**Pull request by roolo**
- Printed magazine
- Magazine's web: https://www.reflex.cz

### CODE REVIEW

**Comment by roolo** [comment]
Noticed there are no tests on a pull request. Shall try to setup something?

**Comment by kovidgoyal** [comment]
I dont keep tests for network resources, they fail too frequently.

**Comment by roolo** [comment]
@kovidgoyal : It could be something just like loading a recipe or something like that. Doesn't have to be exactly test of a function in the code.

**Comment by kovidgoyal** [comment]
What would be the point of such a test?

**Comment by roolo** [comment]
Something like the arguments in the recipe are valid, it contains all the required data/method calls. Automated (pre-)verification of a recipe 🤷🏾 If it fails you know you don't have to even click on the MR.

**Pull request merged**
