### PR TITLE
Bug #1991571: 'Clear' button on short longtext columns. Changed look …

### PR DESCRIPTION
**Pull request by cbhaley**
…to be like the other widgets.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Merged, however, I notice custom series fields dont have a clear button
either.

**Comment by kovidgoyal** [comment]
Sorry, meant to say series index

**Comment by cbhaley** [comment]
That too was intentional. I don't know what it means to clear the series_index. It iis a SpinBox that sn't allowed to be empty. A clear could set it to zero I suppose.

**Comment by kovidgoyal** [comment]
I dont much care, though if you do implement it, it should set to 1 I
think as that is the default series index value.

**Comment by cbhaley** [comment]
I am not going to do it. Two reasons. 1) The code isn't set up to deal with toolbuttons on the second line of 2-line widgets. Significant work (and risk) is required for something I think is minor. 2) The clear button on the Series clears the series_index setting it to 1.0.

**Pull request merged**
