### PR TITLE
The documentation editing tool with changes to support it.

### PR DESCRIPTION
**Pull request by cbhaley**
It is an action so it can be opened easily, should a document writer want to use it. It is also available in the Stored templates / User functions dialog.

It is possible that no one other than me will use it. :)

### CODE REVIEW

**Comment by cbhaley** [comment]
1. How do I run it with calibre-debug -c? I assume there must be some sort of entry point somewhere.
2. What template dialog? The template tester isn't really a place for it because nothing is edited there. The Stored templates dialog uses it to edit the documentation for the user template/function being edited, which isn't the same thing.

**Comment by cbhaley** [comment]
OK, I solved the calibre-debug -c by using if __name__ == '__main__'. The only problem is that it doesn't remember geometry, but that isn't a huge problem.

**Comment by cbhaley** [comment]
FWIW: with this code:
```
if __name__ == '__main__':
    from tempfile import TemporaryDirectory
    from calibre.db.legacy import LibraryDatabase
    from calibre.gui2 import Application

    with TemporaryDirectory() as tdir:
        app = Application([])
        db = LibraryDatabase(tdir) # needed to load formatter_funcs
        d = FFDocEditor(None)
        d.exec()
        del app
```
I get this exception when exiting
```
    with TemporaryDirectory() as tdir:
  File "tempfile.py", line 904, in __exit__
  File "tempfile.py", line 908, in cleanup
  File "tempfile.py", line 890, in _rmtree
  File "shutil.py", line 759, in rmtree
  File "shutil.py", line 617, in _rmtree_unsafe
  File "shutil.py", line 622, in _rmtree_unsafe
  File "tempfile.py", line 881, in onerror
  File "tempfile.py", line 890, in _rmtree
  File "shutil.py", line 759, in rmtree
  File "shutil.py", line 603, in _rmtree_unsafe
  File "shutil.py", line 600, in _rmtree_unsafe
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\Charles\\AppData\\Local\\Temp\\tmpj1_vj_j6\\.calnotes\\notes.db'
```
It leaves the temp directory undeleted.

**Comment by cbhaley** [comment]
Do you object to a non-action keyboard shortcut defined in gui2.ui, similar to 'Minimize the calibre window' and 'focus book list'? This allows someone to easily get to the editor without cluttering up the list of actions. I'd make it discoverable via a comment in formatter_functions.py.

**Comment by kovidgoyal** [comment]
On Wed, Nov 13, 2024 at 06:52:46AM -0800, Charles Haley wrote:
> Do you object to a non-action keyboard shortcut defined in gui2.ui, similar to 'Minimize the calibre window' and 'focus book list'? This allows someone to easily get to the editor without cluttering up the list of actions. I'd make it discoverable via a comment in formatter_functions.py.

That's fine as long as it either defaults to no shortcut or a very
obscure shortcut. Use gui.keyboard.register_shortcut() for it.

**Pull request merged**
