### PR TITLE
New mit_technology_review.recipe

### PR DESCRIPTION
**Pull request by truth1ness**
CSS for body and subtitles, preprocess line breaks, added description, tags, etc.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Your pull request conflicts with current master. Rebase your branch on master and then create the pull request. Something like

git fetch upstream/master
git rebase upstream/master
git push -f

**Comment by truth1ness** [comment]
Ok, I got the rebase upstream/master started but I'm not sure what to do when it gives me the conflict: 

`both added:      recipes/mit_technology_review.recipe`

I tried `git checkout --ours src/MyFile.cs` which is the only thing I could find on resolving this type of error but it didn't seem to do anything.

**Comment by kovidgoyal** [comment]
Just reset your branch to master. Then copy over the changed recipe and make a new commit.

git reset --hard origin/HEAD
cp changed.recipe recipes/mit_technology_review.recipe
git commit -am "whatever"
git push -f

If the first step does not work, you can either fix whatever problems it reports or simpler, just create a new fork.

**Comment by truth1ness** [comment]
Ok, I did the reset, replace the file with a new copy of the recipe, and did the commit and push. Did that work?

**Comment by kovidgoyal** [comment]
Nope, you can check if you have resolved all conflicts by visiting the github page of the pull request. If it shows that the pull request can be automatically merged, you are good. At this point, I suggest you simply close this pull request, delete your fork, create a new fork and a new pull request. That way you will be starting from a clean base.

**Comment by truth1ness** [comment]
Ok, will do. 

Just for my knowledge, did I do anything wrong to cause the repositories to get so hopelessly out of sync or is this normal to have to wipe out a fork just for one file? I've been reading up and watching videos about github for hours to try to understand this so I can fix/avoid it in the future and followed your commands to the letter and I'm still stumped by this one file commit.

**Comment by kovidgoyal** [comment]
Dont read github tutorials, read git tutorials. You dont actually need to delete the fork and start over. You can recover using git commands, however, there is no canned solution for that, because the actions you need to take depend on the actions you took to get into this state. I dont have the time to handhold you through that, so I suggest deleting the fork and starting over.

**Comment by truth1ness** [comment]
Ok, thanks. Yes, I'll keep learning about the process, don't need handholding, just wanted to know if I had made any glaring errors. I have a longer course on Git I'll do next to get a better handle on this.

**Pull request closed without merging**
