### PR TITLE
 Book details panel: Display data in right-to-left format

### PR DESCRIPTION
**Pull request by mushony**
set to a right-to-left language such as Hebrew or Arabic

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Changing the entire html data to right to left unconditionally is not correct. There is no guarantee that the text being displayed is actually right to left. The rest of the book details panel display metadata from the book, which could be in any language. You need to add that code to the HTML in the individual book comment to have it display RTL if appropriate.

**Comment by mushony** [comment]
You can not display the text correctly without using this code.
Although the text display in the right way, but not in the right place.
So that the text look like:


Instead of:

**Comment by mushony** [comment]
By the way,
for LTR languages, the text is still displayed LTR (style="text-align:left")

**Comment by kovidgoyal** [comment]
If you want it aligned right then add the align right to the table not the overall html. Adding it to the overall html will also affect the comments, whose language is not known.

**Pull request closed without merging**
