### PR TITLE
Deleted bloomberg recipe, change in service

### PR DESCRIPTION
**Pull request by dkfurrow**
Hi @kovidgoyal , 
Deleted bloomberg columns recipe that I contributed a month ago.  Pages won't load without a javascript-enabled browser (returns a "violation of service" message).  Bottom line, seems that Selenium works, but mechanize will not.  Unless you know a better way around this, seems like the best thing to do is just delete the recipe.
Thanks,
Dale

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Typically, with these kinds of things, the content is loaded in an invisible part of the page (for search engine optimization) so you can extract it from there. Or alternately it is loaded via AJAX calls which you can simulate in mechanize. But if that is too much work, let me know and I will merge your PR.

**Comment by kovidgoyal** [comment]
Use the network inspector tool in the chrome devtools to see what request is being made by the JS to laod the content, then just duplicate that request in mechanize, no js knowledge needed at all.

**Comment by kovidgoyal** [comment]
I'm not familiar with requests -- never felt the need for it. But it likely has some way to dump the actual HTTP request it makes, use that and compare it with the one mechanize makes. You can get mechanize to dump http requests with

br.set_debug_http(True)

**Comment by 0xInfection** [comment]
Mechanize is no longer supported and should be deprecated.

**Comment by kovidgoyal** [comment]
says who?

**Comment by 0xInfection** [comment]
Oh I just noticed that you're the present maintainer. 😅 Nice.

**Comment by dkfurrow** [comment]
Hi @kovidgoyal; I've gotten busy on some other things, and Bloomberg has changed their website such that the premise of this recipe (the contributors page) no longer exists.  So I'm no longer maintaining this recipe and it's not working.
Thanks,
Dale

**Pull request closed without merging**
