### PR TITLE
Update appstream xml files to current appstream format

### PR DESCRIPTION
**Pull request by norbusan**
Changes:
* replace root node "application" with "component"
* move the "type" attribute from the "id" node to the "component"
* put screenshot urls into "image" nodes
* change installation location to .../metainfo

### CODE REVIEW

**Comment by norbusan** [comment]
Thanks for merging.
Checking with `appstreamcli validate ...` I still get one warning about the naming of files:
`````
W - calibre-gui.appdata.xml:calibre-gui.desktop:3
    The component ID is not a reverse domain-name. Please update the ID and that of 
    the accompanying .desktop file to follow the latest version of the Desktop-Entry 
    and AppStream specifications and avoid future issues.
`````
Do you want a pull request for this, too?

Norbert

**Comment by kovidgoyal** [comment]
No, changing the filename for the desktop file is fairly disruptive and not worth the cost.

**Comment by norbusan** [comment]
I thought so and thus refrained from it. Thanks for the quick answer.

**Comment by petterreinholdtsen** [comment]
Note, the statement "changing the filename for the desktop file is fairly disruptive" seem to indicate that it is believed that changing the file name and ID used in the appstream metadata format also forces a rename of the desktop file.  This is not true.  It is perfectly possible to have a org.reverse.domain.xml appstream file and a something.desktop desktop file by including a `<launchable type="desktop-id">something.desktop</launchable>` tag in the XML file.

**Pull request merged**
