### PR TITLE
Python templates, as discussed at length in …

### PR DESCRIPTION
**Pull request by cbhaley**
…https://www.mobileread.com/forums/showthread.php?t=349525.

I think this is stable, usable, and very close to finished, but I will probably need to react fo feedback, especially yours. :)

### CODE REVIEW

**Comment by cbhaley** [comment]
I pushed a fix for the failing test

**Comment by cbhaley** [comment]
Pushed some changes from un_pogaz.

**Comment by cbhaley** [comment]
Added a few tests for python templates

**Comment by cbhaley** [comment]
un_pogaz pushed a few more changes to the syntax highlighter

**Comment by cbhaley** [comment]
Added another test -- calling a stored python template from a GPM template

**Comment by kovidgoyal** [comment]
I havemerged, looks OK to me. One suggestion I have (which may already
have been discussed, I have not read the full thread on MR) is make the
python function signature

def evaluate(book, ctx):
   ...

Where ctx is an object that carries the db, globals etc as attributes.
Its simpler for users and more easily extensible in the future than
using **kwargs.

**Pull request merged**
