### PR TITLE
Quickview improvements and changes

### PR DESCRIPTION
**Pull request by cbhaley**
See the individual commits for more detail.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Couple of preliminary comments:

1) It is now my policy to insist on having SVG versions of all icons (see the imgsrc directory). PNG icons are generated from them using imgsrc/generate.py

2) At least in wide layout, the layout button should probably be to the right of the cover grid, the rationale being that QV shows up in the cetral panel just like the cover grid and cover browser

**Comment by kovidgoyal** [comment]
You should probably also update the quickview section in the user manual (gui.rst) since it seems to be a little out-of-date

**Comment by cbhaley** [comment]
See the commit comments.

**Comment by kovidgoyal** [comment]
No idea, why this code is from time immemorial :)

**Comment by cbhaley** [comment]
Small change to protect against the Quickview plugin being disabled.

**Comment by cbhaley** [comment]
My apologies for the last two commits. I think I am done now.

**Pull request merged**
