### PR TITLE
Save/reuse ViewLog size plus Saved Search Changes

### PR DESCRIPTION
**Pull request by JimmXinu**
Save/reuse ViewLog size from proceed_question when called with log_viewer_unique_name.

Plugins use proceed_question() to safely update the database.  I'd like to have the ViewLog dialog remember its size when called from my plugin.

This change allows that, but only if proceed_question() is called with parameter log_viewer_unique_name to preserve existing behavior everywhere else.

(I considered using the existing log_viewer_title instead of a new parameter, but thought that was too likely to not be unique.)

### CODE REVIEW

**Comment by kovidgoyal** [comment]
I'm actually OK with just having that dialog remember its size always.

**Comment by JimmXinu** [comment]
It was not my intention to also lump these Saved Search changes in the same Pull Request, but apparently that's how github works.  Sorry about that.

Saved Search Changes:
- Add an empty default entry to the Saved Search Editor drop down.  Otherwise, to see/edit the first saved search you have to select a different one and then select the first again.
- Change Saved Search Editor add button tooltip: From the old tooltip ('Add the new saved search'), I expected to enter the new name and search and then hit 'Add'.  That would change the existing saved search (if one was selected), then create a new, empty one. 'Add a new, empty saved search with the name entered' makes that clear.
- Fix for Saved Search Rename - would add new name, but not remove old name.
- Reset Saved Search combo tooltip when search bars cleared.

**Comment by JimmXinu** [comment]
> I'm actually OK with just having that dialog remember its size always. 

One size for all ViewLog calls, or one size per log_viewer_title?

**Comment by kovidgoyal** [comment]
One size for all.

**Comment by kovidgoyal** [comment]
If you want to use potentially separate names, then I suggest modifying your original patch to have a fallback unique name if the unique name specified by the caller is None. Something like

self.unique_name = unique_name or 'view-log-dialog'

**Comment by JimmXinu** [comment]
> self.unique_name = unique_name or 'view-log-dialog'

Done.

**Pull request merged**
