### PR TITLE
Change to using PIL for image rendering. This lets us do all …

### PR DESCRIPTION
**Pull request by cbhaley**
…thumbnail generation on the cover thread.

I couldn't make the PIL ImageQt stuff work. It seems to use a common butter somewhere. Generating and adding an additional image to the CoverCache corrupted previously added images. This implementation avoids this problem by passing a byte string of the PIL thumbnail to re_render(), which creates the QPixmap on the GUI thread. As a side effect, all the CoverCache operations are now on the GUI thread.

This implementation is visibly faster than the last one.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Hmm looks visibly slower on my system. One tip is instead of using
BytesIO() use ReadOnlyFileBuffer() from speedups.py for Image.open()
Assuming PIL works with fake file objects that return memoryview rather
than bytes that will avoid a whole extra copy of the image data.

Also, I will write a utility function to efficiently convert a PIL image
function to a QPixmap. You are right in that the ImageQt module is
pretty poor. I'll update here once the function is written.

**Comment by kovidgoyal** [comment]
I think I miscommunicated. make_thumbnail is run on a non-GUI thread,
therefore it should return the PIL Image object. The GUI thread should
convert it to a pixmap using convert_PIL_image_to_pixmap
otherwise we are back to using Qt code in a non-GUI thread.

**Comment by kovidgoyal** [comment]
Or maybe make_thumbnail() is called on the GUI thread? The comment at
the start says its called on the cover thread?

**Comment by cbhaley** [comment]
I did put convert_PIL_image_to_pixmap() in the cover thread, which I should have realized wasn't right. The latest commit ensures that just the PIL thumbnail Image is created on the cover thread (no Qt). That image is passed to re_render() on the GUI thread where it is converted to a QPixmap with convert_PIL_image_to_pixmap().

**Comment by kovidgoyal** [comment]
Merged with some optimisations.

**Pull request merged**
