### PR TITLE
Enhancement: allow using templares in search strings

### PR DESCRIPTION
**Pull request by cbhaley**
This is the enhancement I sent you email about. I figured it would be easier to evaluate if you could see it.

### CODE REVIEW

**Comment by cbhaley** [comment]
Second commit: I forgot to enable the template cache when searching.

**Comment by kovidgoyal** [comment]
Looks reasonable, but I am not going to merge it till the dust from
calibre 5 settles. Also could you please add some tests for it to
calibre.db.tests.reading:test_searching

You can run the tests with

calibre-debug src/calibre/db/tests/main.py

**Comment by cbhaley** [comment]
I am trying to add tests and have run into a problem. There is a copy of get_matches in src/library/cache.py. I changed the copy in src/db/search.py. What is the one in src/library for? Is it supposed to be a copy of the one in db?

**Comment by cbhaley** [comment]
Never mind. I found where new search functions are tested.

**Comment by cbhaley** [comment]
I committed some tests

**Comment by kovidgoyal** [comment]
OK I will review after 5

**Comment by kovidgoyal** [comment]
I have merged.

**Pull request closed without merging**
