### PR TITLE
Enhancement #1970045: is_marked() text as tooltip

### PR DESCRIPTION
**Pull request by cbhaley**

### CODE REVIEW

**Comment by kovidgoyal** [comment]
I have merged, it occurs to me you might want to add an "Unmark this
book" action to the context menu when right clicking a row number.

**Comment by cbhaley** [comment]
I think that opens a can of worms. If Unmark then why not Mark? Why not Edit, view, and all the actions on the main context menu? Given that a right click a few mm away gives all of that, why go here?

**Comment by kovidgoyal** [comment]
Mainly because the pins show up on the rows numbers, the rest of the things dont. But it was just a passing thought, not a big deal either way.

**Comment by cbhaley** [comment]
That makes sense. I'll do it.

**Comment by cbhaley** [comment]
Question: it is trivial (and easier) to make it toggle the mark instead of simply clearing it. Should it do that?

**Comment by kovidgoyal** [comment]
yes, makes sense.

**Pull request merged**
