### PR TITLE
Various small fix

### PR DESCRIPTION
**Pull request by un-pogaz**
Three various small fix

1. Add `&` operator and `$` prefix to their doc function
2. Remove space in some functions arguments
3. Fix various unquoted arguments

### CODE REVIEW

**Comment by kovidgoyal** [comment]
@cbhaley please review

**Comment by cbhaley** [comment]
These are all good changes with one exception. That exception: in the commit "add & operator and $ prefix doc" the addition in the second hunk, "The ``$`` prefix can be used instead of the function, as in ``$tags``." is incorrect. The function returns the count of items in a multi-valued field. $field returns the field itself.

**Comment by un-pogaz** [comment]
Hum... crap. I miss the good function to that, I push the fix.

**Comment by cbhaley** [comment]
All good now.

**Pull request merged**
