### PR TITLE
add more Journals from Science

### PR DESCRIPTION
**Pull request by unkn0w7n**

### CODE REVIEW

**Comment by kovidgoyal** [comment]
This is merged, but with different commits as I wanted to keep the larger recipe icons.

**Comment by unkn0w7n** [comment]
oh.. is 32x32 px the standard? i get 16x16 from google.

**Comment by kovidgoyal** [comment]
32x32 looks better with modern high dpi screens.

**Comment by kovidgoyal** [comment]
and i mean looks better in the fetch news dialog in calibre.

**Pull request closed without merging**
