### PR TITLE
Time patch

### PR DESCRIPTION
**Pull request by Volkthehunter**
ignore check modules if they appear

### CODE REVIEW

**Comment by kovidgoyal** [comment]
what does this have to do with calibre?

**Comment by Volkthehunter** [comment]
This is a code that count times elapsed when reading ebooks.

**Comment by kovidgoyal** [comment]
How does it do that? All I can see is checkmodules.py and time.py neither of which do that

**Comment by Volkthehunter** [comment]
It needed to input times and after it's elapsed it will print something.

**Comment by Volkthehunter** [comment]
checkmodule.py is an accident.

**Pull request closed without merging**
