### PR TITLE
update news.py

### PR DESCRIPTION
**Pull request by unkn0w7n**
remove svg and button tags in all recipes.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Removing button is fine, but svg can be useful.

**Comment by kovidgoyal** [comment]
There are some news sources that uses SVG for charts/graphs.

**Comment by unkn0w7n** [comment]
oh.. most graphs i saw were in iframe. 
so adding it to remove tags based on recipe is better.

maybe we can add something like `if svg.findParent('a', attrs={'href':lambda x: x and ('twitter' or 'facebook' or 'wa') in x}):`

**Comment by kovidgoyal** [comment]
On Mon, Feb 12, 2024 at 11:41:08PM -0800, unkn0w7n wrote:
> maybe we can add something like `if svg.findParent('a', attrs={'href':lambda x: x and ('twitter' or 'facebook' or 'wa') in x}):`

It's too dicey, for example

<a href="/article-about-facebook">...<svg>

And in future if new social websites pop up, it will stop working
anyway.

**Pull request closed without merging**
