### PR TITLE
Callable saved GPM templates

### PR DESCRIPTION
**Pull request by cbhaley**

### CODE REVIEW

**Comment by kovidgoyal** [comment]
I'd rather not add another top level entry to Preferences. Instead make it a tab under Template functions.

**Comment by cbhaley** [comment]
Changed to a tabbed dialog. Also embedded the template dialog.

**Comment by kovidgoyal** [comment]
Looks generally OK but I will review it sometime after the next release.

Couple of quick comments:

1) The stored templates tab should probably be second not first
2) Move the scroll bar inside each individual tab, otherwise one large
tab means all the other tabs also take up that height which makes them
hard to use on smaller screen. Basically wrap individual tabs in
QScrollWidgets instead of wraprring th entire tab widget in a scroll.

**Comment by cbhaley** [comment]
Re:
> The stored templates tab should probably be second not first
I disagree. I think that stored templates will be used far more often than template functions. I want the shortcut to go directly to that tab, and the only way to do that is to have it be the first tab.

> scroll bars
OK.

**Comment by kovidgoyal** [comment]
OK, your choice on (1)

**Comment by cbhaley** [comment]
Scrolling tabs pushed.

**Comment by cbhaley** [comment]
Kovid, overnight I thought of 2 improvements I will make:
1) remove the 'call' keyword, making stored templates usable in single function mode
2) cache the parsed stored template, improving performance in single function and template program modes
I will comment here when I finish, which might be Saturday.

**Comment by kovidgoyal** [comment]
Sure, no rush.

**Comment by cbhaley** [comment]
Well, that was a lot easier then I expected. Done.

**Pull request merged**
