### PR TITLE
Enhancement #2062434: Add option to show/edit current column …

### PR DESCRIPTION
**Pull request by cbhaley**
…definition to the booklist header context menu

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Why have a separate view and edit action? A view is just an edit
followed by a cancel, and that context menu is quite long already.

**Comment by cbhaley** [comment]
I added it because of how the existing code works. If you open the dialog, change nothing, and press OK then it is considered edited (requiring a restart), which isn't intuitive. Changing that is more work than I want to do.

I originally had a view/edit menu action with two submenus. I could do that, saving space in the top-level.

Or if you are OK with requiring a restart when OK was pressed when nothing was changed then I can just show "Edit".

**Comment by kovidgoyal** [comment]
I am fine with requiring a restart when doing OK with nothing pressed.
This is not a common operation.

**Comment by cbhaley** [comment]
Changes pushed.

**Pull request merged**
