### PR TITLE
Bug #1950033: Book Details: Missing copy options on composite columns

### PR DESCRIPTION
**Pull request by cbhaley**
Added the copy options as well as search and remove to composites, bools, numbers, etc

### CODE REVIEW

**Comment by kovidgoyal** [comment]
You should make equivalent changes to render_metadata() in
book_details.pyj as well so the metadata display on the content server
also has the same appearance.

**Comment by cbhaley** [comment]
I think I did what you asked for.

Rendering bools does not take the booleans_are_tristate config setting into account. I couldn't figure out how to get that value from db.prefs.

**Comment by cbhaley** [comment]
Note that I did change the behavior. Before it assumed booleans_are_tristate == False. Now it assumes it is True.

**Comment by kovidgoyal** [comment]
I have implemented bools_are_tristate: https://github.com/kovidgoyal/calibre/commit/6322ba9a1b2ba8ae3560702725ebf9504469458f

**Pull request merged**
