### PR TITLE
Update NYT

### PR DESCRIPTION
**Pull request by unkn0w7n**
today's paper recipe

### CODE REVIEW

**Comment by unkn0w7n** [comment]
is nytimes.recipe different from nytimes_sub.recipe?

**Comment by kovidgoyal** [comment]
On Sat, Sep 21, 2024 at 10:35:28PM -0700, unkn0wn wrote:
> is nytimes.recipe different from nytimes_sub.recipe?

These days I dont think so, it used to be in the past. Use diff to
check.

**Comment by kovidgoyal** [comment]
Or actually, no, I think one parses todays page and the other uses
sections.

**Comment by kovidgoyal** [comment]
Basically the two recipes files should be identical, except that is_web_edition is true in one and false in the other. If the nyt requires new parsing code, you should put it in site_parsers/nytimes.py then it can be re-used ina ll nyt recipes without needing to duplicate it in each recipe.

**Comment by unkn0w7n** [comment]
oh.. i think i should just update your code.. its actually pretty similar.

**Pull request closed without merging**
