### PR TITLE
Duplicate of economist.recipe

### PR DESCRIPTION
**Pull request by bobbysteel**
No need for this - at one time there was a need for the "free" recipe but this has not been the case for a while. This recipe seems to be totally duplicate and at best should be renamed as currently there are two identical recipes with the same official title.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
It remains because removing it will break automated news download for people who have subscribed to that recipe in the past.

**Comment by bobbysteel** [comment]
can I suggest renaming one of them then? it's v confusing to have two identical recipes. i'd propose naming this one "The Economist (Free)" for consistency w/ origins.

**Comment by kovidgoyal** [comment]
Since they produce identical output, it would be more misleading to change their titles, since if you name one (Free) and not the other, it would lead people to expect that the other is not free -- which is currently not true.

**Comment by bobbysteel** [comment]
Don't you think it's ridiculous though to have duplicate names that require
code duplication?

**Comment by kovidgoyal** [comment]
No, I dont. I have explained why above.

**Pull request closed without merging**
