### PR TITLE
Enhancement #1886219: In category editor, set focus to selected item

### PR DESCRIPTION
**Pull request by cbhaley**

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Shouldnt this be done only if there is a pre-selected item? Otherwise focusing search is more appropriate

**Comment by cbhaley** [comment]
There is always a preselected item. It is cell 0,0 if no item was passed in. I thought it better to be consistent. Happy to change it if you prefer.

**Comment by kovidgoyal** [comment]
I meant when the dialog is opened by right clicking on the, for example,
"tags" category rather than an individual tag. In such a case, IMO it
makes more sense to focus search rather than the table.

**Comment by cbhaley** [comment]
Done

**Pull request merged**
