### PR TITLE
changes

### PR DESCRIPTION
**Pull request by unkn0w7n**

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Using '1.2 days' as the default will break float(d). Either make the
default '1.2' or use float(d.partition(' ')[0])

**Comment by kovidgoyal** [comment]
in fact, you should probably do something like

```
recipe_specific_options = {
...
'default': str(oldest_article),
}
```

That way you only have to specify the default in one place.

**Comment by kovidgoyal** [comment]
Also, see to keep the recipes compatible with old versions of calibre you use recipe_specific_options like this:

```py
date = self.recipe_specific_options.get('date')
if date and isinstance(date, str):
    ...
```

**Comment by unkn0w7n** [comment]
i'll make those changes

**Comment by unkn0w7n** [comment]
can i use something like this, the default being datetime strftime
```
recipe_specific_options = {
        'date': {
            'short': 'The date of the print edition to download (DD-MM-YYYY format)',
            'long': 'For example, 20-09-2023',
            'default': datetime.today().strftime('%d-%m-%Y')
        }
    }
```
It seems to work, but i wanted to ask. 
But wouldn't the recipe need to run, to get that datetime to show up as default in that advanced menu?

**Comment by unkn0w7n** [comment]
I realize it won't be compatible with previous versions of calibre.
```
   recipe_specific_options = {
        'date': {
            'short': 'The date of the edition to download\nlower case Month-DD-YYYY format',
            'long': 'For example, july-12-2024',
            'default': 'current-issue'
        }
    }

    def parse_index(self):
        # issue = 'https://www.the-tls.co.uk/issues/current-issue/'

        d = self.recipe_specific_options.get('date')
        if d and isinstance(d, str):
            issue = 'https://www.the-tls.co.uk/issues/' + d + '/'
```
It would require mentioning default again for old recipes anyhow.

**Comment by kovidgoyal** [comment]
No, you cant do that. the date in self.recipe_options has to be serializable as JSON.

**Comment by unkn0w7n** [comment]
can i use this on reuters? i removed the default and still kept the oldest_article. if theres user input, it'll override the oldest_recipe from code.
```
    oldest_article = 1.2 # days
    recipe_specific_options = {
        'days': {
            'short': 'Oldest article to download from this news source. In days ',
            'long': 'For example, 0.5, gives you articles for the past 12 hours',
        }
    }

    def __init__(self, *args, **kwargs):
        BasicNewsRecipe.__init__(self, *args, **kwargs)
        d = self.recipe_specific_options.get('days')
        if d and isinstance(d, str):
            self.oldest_article = float(d)

    def parse_index(self):
        index = 'https://www.reuters.com'
```

Also, for TLS i'll use this... so that recipe_spec_optns work with default but i'll also mention link to work with old recipes.

```
   recipe_specific_options = {
        'date': {
            'short': 'The date of the edition to download\nlower case Month-DD-YYYY format',
            'long': 'For example, july-12-2024',
            'default': 'current-issue'
        }
    }

    def parse_index(self):
        issue = 'https://www.the-tls.co.uk/issues/current-issue/'

        d = self.recipe_specific_options.get('date')
        if d and isinstance(d, str):
            issue = 'https://www.the-tls.co.uk/issues/' + d + '/'
```

**Comment by kovidgoyal** [comment]
On Sat, Jul 20, 2024 at 08:59:59PM -0700, unkn0wn wrote:
> can i use this on reuters? i removed the default and still kept the oldest_article. if theres user input, it'll override the oldest_recipe from code.
> ```
>     oldest_article = 1.2 # days
>     recipe_specific_options = {
>         'days': {
>             'short': 'Oldest article to download from this news source. In days ',
>             'long': 'For example, 0.5, gives you articles for the past 12 hours',

Add the default here as

'default': str(oldest_article),

this will work fine as it gets evaluated to "1.2" which is a constant
value unlike date.today() which is not (the date will depend on when the
serialization to json is done).

> Also, for TLS i'll use this... so that recipe_spec_optns work with default but i'll also mention link to work with old recipes.
>
> ```
>    recipe_specific_options = {
>         'date': {
>             'short': 'The date of the edition to download\nlower case Month-DD-YYYY format',
>             'long': 'For example, july-12-2024',
>             'default': 'current-issue'
>         }
>     }
>
>     def parse_index(self):
>         issue = 'https://www.the-tls.co.uk/issues/current-issue/'
>
>         d = self.recipe_specific_options.get('date')
>         if d and isinstance(d, str):
>             issue = 'https://www.the-tls.co.uk/issues/' + d + '/'
> ```

That's fine.

**Comment by unkn0w7n** [comment]
> 'default': str(oldest_article),

i'll use it
> unlike date.today() which is not (the date will depend on when the
serialization to json is done).

Hmmm too bad.
It seems to work nicely though. Idk how its executing datetime.now() but it worked without me running the recipe today.
image

**Comment by kovidgoyal** [comment]
On Sat, Jul 20, 2024 at 09:10:38PM -0700, unkn0wn wrote:
> > 'default': str(oldest_article),
>
> i'll use it
> > unlike date.today() which is not (the date will depend on when the
> serialization to json is done).
>
> Hmmm too bad.
> It seems to work nicely though. Idk how its executing datetime.now() but it worked without me running the recipe today.
> image

That's because you are presumably testing it as a custom recipe. Custom
recipes are evaluated each time you run the dialog. Builtin recipes get
their metadata serialized at calibre build time in
resources/builtin_recipes.xml

**Pull request closed without merging**
