### PR TITLE
Fix cover resolution and add log line

### PR DESCRIPTION
**Pull request by bobbysteel**
Current method does not pull highest resolution available but instead a very low quality thumbnail

### CODE REVIEW

**Comment by kovidgoyal** [comment]
The last time I checked, the higher resolution images served by the economist servers were just upscaled versions of the thumbnail cover, so it was pointless downloading them. Has that changed?

**Comment by bobbysteel** [comment]
It's definitely upscaling a bit but better than the 200px ones now. the
200px doesn't even appear on the new Kindle Oasis weirdly presumably since
it's too small.

**Comment by kovidgoyal** [comment]
Hmm, well to me the 640 one looks better than the 1200 one. Less pixelated and large enough to serve as a thumbnail in most places. No point wasting all that bandwidth for higher than that.

**Comment by bobbysteel** [comment]
Fair enough - I'll edit now

**Comment by bobbysteel** [comment]
Updated to 640px width per Kovid's comment

**Pull request merged**
