### PR TITLE
Rework setting up document stats

### PR DESCRIPTION
**Pull request by MisterAP**
Improve the setup of document stats to fix bug 2089436.
Rationalising some variable names.
Fixes to merging pages.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Can you please rebase on origin/master and then do a force push to
update the pull request.

**Comment by MisterAP** [comment]
I hope I have done that.
My source says it is now up to date.


There are/were differences in tabs/spaces on a few lines.  I don't see anything else.

Mister P

On Friday 20 December 2024 14:13:24 (+00:00), Kovid Goyal wrote:



Can you please rebase on origin/master and then do a force push to
update the pull request.

**Comment by kovidgoyal** [comment]
No your PR still has multiple commits in it. I suggest you first save
the reflow.py file, then do

git reset --hard origin/master
then copy back the reflow.py file
then do
git commit -a && git push -f

Also looking at your diff, last_line seems to be defined after it is
first used. First used on line 1960 and defined on line 2002. I didnt
read it in detail but probably should be fixed.

**Comment by MisterAP** [comment]
Hmmm.


I've fixed the last_line problem.  Interestingly it did not crash any of my tests.


Everything in git says it has worked, but my github source is still old, even after a forced push.
I can't push direct to your source as that would need write permission.


Am I missing something?

Mister P

On Friday 20 December 2024 16:52:20 (+00:00), Kovid Goyal wrote:



No your PR still has multiple commits in it. I suggest you first save
the reflow.py file, then do

git reset --hard origin/master
then copy back the reflow.py file
then do
git commit -a && git push -f

Also looking at your diff, last_line seems to be defined after it is
first used. First used on line 1960 and defined on line 2002. I didnt
read it in detail but probably should be fixed.

**Comment by kovidgoyal** [comment]
No sadly that didnt work, but I have extracted your changes and made the commit myself. I suggest you delete your calibre fork and do a fresh checkout. Easiest way to get it back into a good state.

**Comment by MisterAP** [comment]
Thanks for your work.


I have re-synced everything, and my PC and GitHub are up-to-date.

Mister P

On Saturday 21 December 2024 03:04:24 (+00:00), Kovid Goyal wrote:



No sadly that didnt work, but I have extracted your changes and made the commit myself. I suggest you delete your calibre fork and do a fresh checkout. Easiest way to get it back into a good state.

**Pull request closed without merging**
