### PR TITLE
Bug #1927179: VL set to wildcard crashes Calibre. …

### PR DESCRIPTION
**Pull request by cbhaley**
…Note that the problem had nothing to do with wildcards. It was triggered by an unanchored search specification (one with no column), which caused all the composite columns to be evaluated.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
I'm a little concerned about clearing the cache without a write lock. Is it really always safe for multiple threads to concurrently access the cache while it can be modified? Is there some reason we cant modify virtual_libraries_for_books to use more granular locking. i.e. use `@api` and then acquire the read and write locks as needed inside the function body

**Comment by cbhaley** [comment]
I would be happier doing it right. The problem is that I don't know how. I will try to figure out granular locking.

**Comment by kovidgoyal** [comment]
Just put the sections that requir read locking in 

with self.read_ock:
  ...

and then clear the cache in a wite self.write_lock block

the only subtety would be to make sure that releasing the locks outside
the blocks is not an issue.

**Comment by cbhaley** [comment]
There is no way to acquire a write lock in virtual_libraries_for_books() because it is called by get_metadata() that has already acquired a read lock.

I have another idea for how to do it -- clear the cache in view.virtual_libraries_for_books() instead of in cache.virtual_libraries_for_books(). More later ...

**Comment by cbhaley** [comment]
I ended up clearing the composite cache in cache.get_metadata().

**Comment by kovidgoyal** [comment]
On Wed, May 05, 2021 at 08:48:40AM -0700, Charles Haley wrote:
> I ended up clearing the composite cache in cache.get_metadata().

I have merged, changing the code slightly to hold a read lock when
checking if the cache needs to be rebuilt. Also I dont quite follow why
we need to check for a DowngradeLockError. A DowngradeLockError happens
when you try to acquire a read lock while holding a write lock. This is
what safe_read_lock guards against.

**Comment by cbhaley** [comment]
The DowngradeLockError was a mistake. I misremembered the exception I was seeing when I tried to use write locks in virtual_libraries_for_books().

However, the change you made points to another problem. The method virtual_libraries_for_books() is protected by a shared read lock. This means that in theory multiple threads could be refilling the cache because the test for recursion is not protected. What a newbie mistake. I will fix it to use a gateway lock then make another PR.

**Pull request merged**
