### PR TITLE
py3: add polyglot wrapper for cPickle and use it everywhere

### PR DESCRIPTION
**Pull request by eli-schwartz**
Actually, almost everywhere. src/calibre/utils/config_base.py uses it twice, but both times it shouldn't matter as it is only being used to proxy/load settings files, so they should probably be left alone in order to preserve people's settings.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
I dont think it is going to be quite that simple -- unpickling python 2 data on python 3 is not at all straighforward see for instance https://stackoverflow.com/questions/28218466/unpickling-a-python-2-object-with-python-3

**Comment by kovidgoyal** [comment]
pickle is really a bad idea anyway. I'd like to instead excise it from the calibre codebase as much as possible. I've been meaning to do that, but been lazy since there is no overriding need apart from the general bad-ness of pickle.

**Comment by eli-schwartz** [comment]
Ugh.

Haven't thought about data migration at all, really, was just trying to get it to start up. :p Feel free to add a data migration hook or ignore this PR, whichever suits you best.

**Comment by kovidgoyal** [comment]
I have migrated all uses of cPickle except for the ones in the config files, because of the afore-mentioned data portability issues, Will need to investigate how feasible moving the .py and .pickle config files to json is.

**Comment by eli-schwartz** [comment]
Great!

**Pull request closed without merging**
