### PR TITLE
Enhancement: add a tweak to provide the sort value for undefined …

### PR DESCRIPTION
**Pull request by cbhaley**
…numbers.

I couldn't find a case where numeric_sort_key() was called with a non-number but I decided to add the test anyway.

The change to tweaks.py fixes something that has annoyed me for a long time. I don't know if the problem exists on other platforms. If it doesn't then perhaps it could be conditioned with an 'if windows' test.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Rather than initializing the constant at import time, initialize it in Field.__init__ that way changing the tweak doesn't require a restart. This is how the tweak for sorting times is also applied so I doubt it makes a significant performance difference.

As for the horizontal scrollbar, I cant get  horizontal scrollbar to show up at all on windows or linux. Since the text in the list of tweaks is word wrapped why would there be a horizontal scrollbar? Do you have a custom tweak with a very long name and no spaces in the name? If that's the case the correct fix would be to change the data() method to force wrap things longer than 40 chars.

**Comment by cbhaley** [comment]
The horizontal scrollbar problem is related to font size. The width of the list and the number-of-characters word wrap point are hard coded, so the bar appears for bigger fonts. I have an implementation that computes the word wrap point based on the text and the font. I will push it shortly.

**Comment by cbhaley** [comment]
As for the tweak, I changed it. However it seems that Preferences / tweaks (Tweaks.commit()) doesn't change the internal tweak dictionary so a restart is still required. This is true for the date tweak as well. However, it is worth doing so changing it can be moved easily to the gui if wanted.

**Comment by kovidgoyal** [comment]
I have merged with a simpler solution for word wrapping in the tweaks
view, letting Qt handle it. The scrollbar doesnt show up for me anymore.

**Comment by cbhaley** [comment]
Your change is much better! However, note that in some cases it uses ellipses instead of wrapping. See image. I am OK with that
Clipboard01
.

**Pull request closed without merging**
