### PR TITLE
convert the text for Semitic Languages

### PR DESCRIPTION
**Pull request by mushony**
convert the text for Semitic Languages - for example:
text like this:
"author:   someone"
Looks like this, in Semitic Languages :
"someone  :author"
its necessary for good display to these languages

### CODE REVIEW

**Comment by kovidgoyal** [comment]
I'm somewhat confused by this pull request. What are you trying to achieve? You want labels to be the second column in the book details panel when the calibre user inteface language is a RTL langugae like Hebrew? 

The correct way to do that is to change the the mi_to_html() function to generate the table with the desired layout when passed a parameter rtl=True.

You can detect when to set rtl=True by checking the value of get_lang() from calibre.utils.localization. You would need to chech for both hebrew and arabic language codes.

**Comment by kovidgoyal** [comment]
See https://github.com/kovidgoyal/calibre/commit/c33017583e4ac0663405276efd0f66b255af340c

**Comment by mushony** [comment]
Very well.
But I found a small bug in the final display of book details.
This can be remedied only a in the file "book_details.py".
I'll upload the fixed code.
By the way, where I can convert the main window of the library (RTL), like you did here?

**Comment by kovidgoyal** [comment]
You call QApplication::setLayoutDirection() However I would not recommend doing that, as it has very radical effects that are likely to break many things.

**Pull request closed without merging**
