### PR TITLE
MitTechnologyReview.recipe

### PR DESCRIPTION
**Pull request by truth1ness**

### CODE REVIEW

**Comment by kovidgoyal** [comment]
I just added this recipe based on your post on mobileread, since I saw that first. In the future, just use Pull Requests, that way you will get "credit" for them on github.

**Comment by truth1ness** [comment]
Ah, ok. This was my first github submission so I wasn't sure if it would work. Do you think you could use this one instead since I don't have anything else in my name on Github? Thanks!

**Comment by kovidgoyal** [comment]
No, I'm afraid not, that would create churn in the calibre commit history. Think of it as motivation to write another recipe :)

**Comment by kovidgoyal** [comment]
ALso just a note for the future, the recipe file naming convention in calibre is all lowercase with underscrores. So your recipe file should have been named mit_technology_reciew.recipe

**Comment by truth1ness** [comment]
Aw, boo. Just one exception for a first timer? I'm OCD about keeping my stuff together! (And this took me an embarrassing number of hours to figure out). I also posted on the forum first because I thought you or other people might want to run/check it locally before allowing it to be added to Github. I really had no idea how Github works and if it had to be 'cleared' first.

**Comment by kovidgoyal** [comment]
Make some small improvement to the recipe, for example, adding extra_css to improve formatting and create a new pull request for it, I will be happy to merge that.

**Comment by truth1ness** [comment]
Ok, will do. Thanks!

**Pull request closed without merging**
