### PR TITLE
Error Trying to Create a New Short Cut ，How to fix it

### PR DESCRIPTION
**Pull request by zhl111**
calibre, version 5.33.2
错误： 未处理的异常: <b>TypeError</b>:unsupported operand type(s) for |: 'int' and 'KeyboardModifiers'

calibre 5.33.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: zh_CN
Traceback (most recent call last):
  File "calibre\gui2\keyboard.py", line 492, in eventFilter
  File "calibre\gui2\keyboard.py", line 499, in key_press_event
  File "calibre\gui2\keyboard.py", line 46, in keysequence_from_event
TypeError: unsupported operand type(s) for |: 'int' and 'KeyboardModifiers'
image

### CODE REVIEW

**Comment by kovidgoyal** [comment]
https://www.mobileread.com/forums/showthread.php?t=343490

**Comment by zhl111** [comment]
Haha, I saw this post before, but I don't know programming or how to modify it, very sorry

**Comment by kovidgoyal** [comment]
You wait for the next release or downgrade to 5.32 in the meantime

**Comment by zhl111** [comment]
ok，thanks

**Pull request closed without merging**
