### PR TITLE
Rewrite much of the template language manual document.

### PR DESCRIPTION
**Pull request by cbhaley**
The commit on 27 Feb isn't good. The manual page should be regenerated from this commit.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
the manual has been rebuilt

**Comment by cbhaley** [comment]
Kovid, do you know why the grammar starting at line 195 isn't rendered as a fixed block?  Is the ::= confusing the parser? Or is it the 'sphinx warnings' you made changes in the previous version to remove?

**Comment by kovidgoyal** [comment]
Its rendered as a block for me and there are currently no warnings. did you hit refresh in your browser?
Screenshot_20210228_223840

**Comment by cbhaley** [comment]
I hadn't hit refresh. Sorry about the noise.

**Pull request merged**
