### PR TITLE
Enhancement: allow simultaneous editing in the category editor. …

### PR DESCRIPTION
**Pull request by cbhaley**
…Select multiple items (tags, whatever), then edit. When you finish editing, all the items will change to the edited value.

Kovid, this change was part of an enhancement request, but I am not convinced that it is a good change to make. What do you think? If you think it is benign, go ahead and accept it.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
For this to be workable, there needs to be some indication that editing the current cell will change all selected cells, maybe change the display of selected but not editing cells to "editing" or similar.

**Comment by cbhaley** [comment]
Pushed a change to mark the other rows with *** EDITING ***. This is a bit fiddly because AFAIK qt doesn't tell me if editing has been abandoned with no changes. I had to trap key events.

**Comment by kovidgoyal** [comment]
As I recall editors can be closed by clicking else where in the table as well. Is subclassing the item delegate and overriding createEditor() and destroyEditor() not sufficient?

**Comment by cbhaley** [comment]
I was looking for a signal and didn't see the editorDestroyed method. It seems to work correctly now.

**Pull request merged**
